"""Set google_place_id as PK for Place, update Review FK and model

Revision ID: 62e963ef849a
Revises: ed27bbe8f6b7
Create Date: 2025-04-20 23:39:28.757248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# PostgreSQL 특정 타입 사용 시 필요할 수 있음 (예: JSON)
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62e963ef849a'
down_revision: Union[str, None] = 'ed27bbe8f6b7' # 이전 리비전 ID 확인 필요
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### 수동으로 순서 조정한 Alembic 명령어 ###

    # 1. 기존 Review -> Place FK 제약 조건 삭제
    op.drop_constraint('reviews_place_id_fkey', 'reviews', type_='foreignkey')

    # 2. 기존 Review의 FK 컬럼 ('place_id') 삭제 (선택 사항, 아래에서 새 FK 컬럼 추가 시 덮어쓸 수도 있음)
    #    인덱스도 함께 삭제해야 함
    op.drop_index('ix_reviews_place_id', table_name='reviews')
    # op.drop_column('reviews', 'place_id') # 아래에서 어차피 추가/변경되므로 생략 가능성 있음 (스크립트 생성 방식 따라 다름)

    # 3. 기존 Place의 PK 컬럼 ('id') 삭제
    #    인덱스도 함께 삭제해야 함
    op.drop_index('ix_places_id', table_name='places')
    # --- 주의: PK 제약 조건을 먼저 삭제해야 할 수도 있음 (DB 종류/Alembic 버전에 따라) ---
    # op.drop_constraint('places_pkey', 'places', type_='primary') # PK 제약조건 이름 확인 필요
    op.drop_column('places', 'id')

    # 4. Place 테이블의 google_place_id를 PK로 설정
    #    기존 인덱스 삭제 (만약 있었다면) 및 PK 제약 조건 생성
    op.drop_index('ix_places_google_place_id', table_name='places') # 이전 스크립트에서 unique=False로 잘못 만들었던 인덱스 삭제
    op.alter_column('places', 'google_place_id',
               existing_type=sa.VARCHAR(),
               nullable=False) # Nullable False 확인
    # PK 제약조건 직접 생성 (제약조건 이름은 DB가 자동 생성하도록 None 가능)
    op.create_primary_key(None, 'places', ['google_place_id'])
    # PK 컬럼에 대한 인덱스 재생성 (Alembic 기본값은 PK 컬럼에 자동 인덱스 생성)
    op.create_index(op.f('ix_places_google_place_id'), 'places', ['google_place_id'], unique=True) # PK는 unique=True

    # 5. Place 테이블의 user_ratings_total 타입 변경 (Float -> Integer)
    op.alter_column('places', 'user_ratings_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               postgresql_using='user_ratings_total::integer', # PostgreSQL 타입 캐스팅
               existing_nullable=True)

    # 6. Place 테이블의 rating 컬럼 추가 (기존 google_rating은 이전 마이그레이션에서 삭제됨 가정)
    #    만약 이전 마이그레이션(ed27bbe8f6b7)이 실패했었다면, 여기서 컬럼 이름을 변경해야 함
    #    이전 마이그레이션(ed27bbe8f6b7)이 성공했다면 아래 코드가 맞음
    # op.add_column('places', sa.Column('rating', sa.Float(), nullable=True)) # ed27bbe8f6b7 에서 처리됨 가정

    # 7. Review 테이블에 새 FK 컬럼 및 기타 컬럼 추가
    op.add_column('reviews', sa.Column('place_google_id', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('author_name', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('relative_time_description', sa.String(), nullable=True))

    # 8. Review 테이블의 새 FK 컬럼에 대한 인덱스 생성
    op.create_index(op.f('ix_reviews_place_google_id'), 'reviews', ['place_google_id'], unique=False)

    # 9. Review 테이블에 새 FK 제약 조건 생성
    op.create_foreign_key(None, 'reviews', 'places', ['place_google_id'], ['google_place_id']) # 제약 조건 이름 자동 생성

    # 10. Review 테이블의 기존 content 컬럼 삭제
    op.drop_column('reviews', 'content')

    # 11. Review 테이블의 기존 place_id 컬럼 삭제 (2번에서 삭제 안했다면 여기서)
    op.drop_column('reviews', 'place_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade는 복잡하므로 자동 생성된 코드를 기반으로 신중하게 역순으로 구성해야 함
    # 여기서는 upgrade에 집중하므로 downgrade 로직은 단순화/생략
    op.add_column('reviews', sa.Column('place_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('reviews_place_google_id_fkey', 'reviews', type_='foreignkey') # 생성 시 이름 확인 필요 (None이면 자동생성된 이름)
    op.create_foreign_key('reviews_place_id_fkey', 'reviews', 'places', ['place_id'], ['id'])
    op.drop_index(op.f('ix_reviews_place_google_id'), table_name='reviews')
    op.create_index('ix_reviews_place_id', 'reviews', ['place_id'], unique=False)
    op.drop_column('reviews', 'relative_time_description')
    op.drop_column('reviews', 'profile_photo_url')
    op.drop_column('reviews', 'author_name')
    op.drop_column('reviews', 'text')
    op.drop_column('reviews', 'place_google_id')

    op.add_column('places', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('places_pkey', 'places', type_='primary') # PK 제약 조건 이름 확인 필요
    op.create_primary_key('places_pkey', 'places', ['id'])      # PK 제약 조건 이름 확인 필요
    op.drop_index(op.f('ix_places_google_place_id'), table_name='places')
    op.create_index('ix_places_google_place_id', 'places', ['google_place_id'], unique=True) # 이전 상태가 unique=True 였는지 확인 필요
    op.create_index('ix_places_id', 'places', ['id'], unique=False)
    # places 테이블 rating, user_ratings_total 복구 로직 필요...
    # ### end Alembic commands ###