"""Final attempt Place PK and Review FK changes

Revision ID: 6c962760db57
Revises: 62e963ef849a
Create Date: 2025-04-21 00:09:39.298290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c962760db57'
down_revision: Union[str, None] = '62e963ef849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_google_place_id', table_name='places')
    op.create_index(op.f('ix_places_google_place_id'), 'places', ['google_place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_google_place_id'), table_name='places')
    op.create_index('ix_places_google_place_id', 'places', ['google_place_id'], unique=True)
    # ### end Alembic commands ###
