"""empty message

Revision ID: 9d85c864060d
Revises: 42333becda6f
Create Date: 2025-04-21 21:33:12.745627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d85c864060d'
down_revision: Union[str, None] = '42333becda6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('places', sa.Column('operating_hours', postgresql.ARRAY(sa.String()), nullable=True))
    # op.add_column('places', sa.Column('image_url', sa.String(), nullable=True))  # <-- Comment out or remove this line
    # op.add_column('places', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))  # Already exists, so comment out
    # op.add_column('places', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))  # Already exists, so comment out
    op.alter_column('places', 'types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('places', 'types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="ARRAY(SELECT jsonb_array_elements_text(types::jsonb))",
               existing_nullable=True)
    op.alter_column('places', 'photo_references',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('ix_places_name', table_name='places')
    op.create_index(op.f('ix_places_created_at'), 'places', ['created_at'], unique=False)
    # op.add_column('reviews', sa.Column('author_name', sa.String(), nullable=True))  # Already exists, so comment out
    op.add_column('reviews', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('relative_time_description', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_reviews_id', table_name='reviews')
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_owner_id'), 'reviews', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reviews_place_google_id'), 'reviews', ['place_google_id'], unique=False)
    op.drop_constraint('routes_owner_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_travel_routes_id'), 'travel_routes', ['id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_travel_routes_id'), table_name='travel_routes')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_owner_id_fkey', 'routes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reviews_place_google_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_owner_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.create_index('ix_reviews_id', 'reviews', ['id'], unique=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'relative_time_description')
    op.drop_column('reviews', 'profile_photo_url')
    op.drop_column('reviews', 'author_name')
    op.drop_index(op.f('ix_places_created_at'), table_name='places')
    op.create_index('ix_places_name', 'places', ['name'], unique=False)
    op.alter_column('places', 'photo_references',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('places', 'types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_column('places', 'created_at')
    op.drop_column('places', 'tags')
    op.drop_column('places', 'image_url')
    op.drop_column('places', 'operating_hours')
    # ### end Alembic commands ###
