"""empty message

Revision ID: abc5700be2a3
Revises: d2de66c4e886
Create Date: 2025-04-21 16:57:37.944170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc5700be2a3'
down_revision: Union[str, None] = 'd2de66c4e886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_owner_id', table_name='reviews')
    op.drop_index('ix_reviews_place_google_id', table_name='reviews')
    op.drop_index('ix_reviews_rating', table_name='reviews')
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'author_name')
    op.drop_column('reviews', 'profile_photo_url')
    op.drop_column('reviews', 'relative_time_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('relative_time_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('ix_reviews_rating', 'reviews', ['rating'], unique=False)
    op.create_index('ix_reviews_place_google_id', 'reviews', ['place_google_id'], unique=False)
    op.create_index('ix_reviews_owner_id', 'reviews', ['owner_id'], unique=False)
    # ### end Alembic commands ###
