"""create places table

Revision ID: fcf701860466
Revises: 2c62463e58ab
Create Date: 2025-04-20 21:10:13.401768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf701860466'
down_revision: Union[str, None] = '2c62463e58ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Float(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('photo_references', sa.JSON(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_google_place_id'), 'places', ['google_place_id'], unique=True)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_google_place_id'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
